### ISSUE TITLE
database optimisation using prisma acceleration

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/pecha-tool-for-sentence-segmentation#5]
### Description

when the annotator is done with the database . it seems as if the reviewer are taking a lot of time to fetch the data, 
we need to speed it up .

### Completion Criteria
time taker of a data to fetch in reviewer ui should be down significantly

### Implementation Plan
i am gonna implement prisma Client acceleration method , so that the non updating data get cached and the load time become faster

### Sub-tasks
- [x] make a console prisma account
- [x] generate API endpoint for the prisma account for acceleration
- [x] config acceleration api on tool
- [ ] modify non updating database queries with cache system

**Comment by tenkus47** [comment]
since acceleration is paid after several request we need to apply a cache mechanism ourself to make app faster
