### ISSUE TITLE
load optional data on click.

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/pecha-tool-for-sentence-segmentation#6]
### Description
rite now all the user data and history are loaded during the render automatically which is not so much needed, if we can make a button to fetch the history and some neccesary data on command, that will be much faster due to less computation on query side

### Completion Criteria
the UI need to be a lot faster than what it is now.

### Implementation Plan

i have to update ui for a trash mechanism with which the side bar data need not to be loaded when started , and on a click of a button user will be able to load the history and all related meta datas

### Sub-tasks
- [x] mechanism for trashing Text
- [x] hide sidebar meta datas
- [x] fetch meta datas on a click
- [x] maintain Url params on submission of task
- [x] reviewer page needs a trashing button
