### ISSUE TITLE
sentence segmentation submit get stuck

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/pecha-tool-for-sentence-segmentation#7]
## Introduction
 
sentence segmentation submit button stuck after each submit of data. 

## Objectives

when a user click on submit button the process get stuck at loading, we need to solve it  . this mostly happen once after every 20 or 30 submits. must be a remix bug , as mentioned here:

https://github.com/remix-run/remix/issues/8298

![Image](https://github.com/OpenPecha/pecha-tool-for-sentence-segmentation/assets/42644738/bd6460fe-f139-4e81-af97-7fb7f96a184c)

## Completion Criteria

the final product should not get stuck on loading when user submit a data, 

## Implementation Plan

Subtasks
 - [x] test api submiting with axios
 - [x] test api with fetch API 
 - [x] interval revalidation , check if it solves the issue
